[build]
packages = ["python3", "python3Packages.pip", "gcc", "libffi", "openssl"]

[phases.setup]
commands = ["python3 -m ensurepip", "python3 -m pip install --upgrade pip", "pip3 install -r requirements.txt"]

[phases.start]
commands = ["python3 bexx.py"]

[build.environment]
PYTHON_VERSION = "3.9"
