[build]
packages = ["python3", "python3Packages.pip", "gcc"]

[phases.setup]
commands = ["python -m ensurepip", "python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
commands = ["python bexx.py"]

[build.environment]
PYTHON_VERSION = "3.9"


