[build]
packages = ["python3", "python3Packages.pip", "gcc", "libffi", "openssl"]

[phases.setup]
commands = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
commands = ["python bexx.py"]

[build.environment]
PYTHON_VERSION = "3.9"
