[build]
packages = ["python311", "python3Packages.pip", "gcc", "libffi", "openssl", "zlib"]

[phases.setup]
commands = ["python3 -m pip install --no-cache-dir -r requirements.txt"]

[phases.start]
commands = ["python3 bexx.py"]





