[build]
packages = ["python3", "python3Packages.pip", "gcc"]

[phases.setup]
commands = ["pip3 install --upgrade pip", "pip3 install -r requirements.txt"]

[phases.start]
commands = ["python3 bexx.py"]

[build.environment]
PYTHON_VERSION = "3.9"


