[build.environment]
PYTHON_VERSION = "3.9"

[phases.setup]
commands = [
  "python3 -m ensurepip",
  "python3 -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
commands = ["python bexx.py"]
